export const ADD_FRIEND = 'ADD_FRIEND';
export const STAR_FRIEND = 'STAR_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';

export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS';
export const CHECK_LOGIN_FAILED = 'CHECK_LOGIN_FAILED';
export const CHECK_LOGIN_REQUEST = 'CHECK_LOGIN_REQUEST';

export const PRELOADER_START = 'PRELOADER_START';
export const PRELOADER_STOP = 'PRELOADER_STOP';