export const ADD_FRIEND = 'ADD_FRIEND';
export const STAR_FRIEND = 'STAR_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';

export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS';
export const CHECK_LOGIN_FAILED = 'CHECK_LOGIN_FAILED';
export const CHECK_LOGIN_REQUEST = 'CHECK_LOGIN_REQUEST';

export const PRELOADER_START = 'PRELOADER_START';
export const PRELOADER_STOP = 'PRELOADER_STOP';

export const SET_TOKEN_TO_SOCKET = 'SET_TOKEN_TO_SOCKET';
export const SET_DATA_AFTER_AUTH = 'SET_DATA_AFTER_AUTH';
export const CHANGE_CHAT = 'CHANGE_CHAT';